version: "3"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - mssqldbdata:/var/opt/mssql
    #restart: always
    container_name: sqlserver2017
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "@SQLserverpa55"
      MSSQL_PID: "Express"

volumes:
  mssqldbdata:
